name: publish
concurrency: ${{ github.workflow }}-${{ github.ref }}
on:
  push:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: 🟢 Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: ⚙️ Install dependencies
        run: bun install
      - name: 🚀 Create Pull Request & Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: bun changeset publish
          commit: "✅ chore: update version"
          title: "✅ chore: update version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
